import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import path from 'path';
import fs from 'fs-extra';
import { fileURLToPath } from 'url';
import { Kiteretsu, Scanner, FileClassifier } from '../src/index.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR = path.resolve(__dirname, '../../../test-fixtures/pathological-repo');
const TEMP_ROOT = path.join(__dirname, 'temp_test_pathological');

describe('Pathological Repository & OOM Protection Suite', () => {
  let kiteretsu: Kiteretsu;

  beforeAll(async () => {
    await fs.remove(TEMP_ROOT);
    await fs.copy(FIXTURE_DIR, TEMP_ROOT);

    kiteretsu = new Kiteretsu({
      rootDir: TEMP_ROOT,
      indexing: {
        maxFileSize: '1MB'
      }
    });
    await kiteretsu.init();
  });

  afterAll(async () => {
    if (kiteretsu) {
      await kiteretsu.destroy();
    }
    await fs.remove(TEMP_ROOT);
  });

  it('FileClassifier accurately classifies generated, binary, vendor, and source files across multi-language ecosystems', () => {
    // JS / TS / Web
    expect(FileClassifier.classify('.next/static/chunks/huge-chunk.js').classification).toBe('generated');
    expect(FileClassifier.classify('public/_next/static/chunks/0v3lyuj75aq50.js').classification).toBe('generated');
    expect(FileClassifier.classify('dist/bundle.js').classification).toBe('generated');
    expect(FileClassifier.classify('node_modules/express/index.js').classification).toBe('vendor');

    // Python
    expect(FileClassifier.classify('__pycache__/model.cpython-311.pyc').classification).toBe('binary');
    expect(FileClassifier.classify('.pytest_cache/v/cache/nodeids').classification).toBe('generated');
    expect(FileClassifier.classify('.venv/lib/python3.11/site-packages/flask.py').classification).toBe('vendor');
    expect(FileClassifier.classify('src/generated.py', '# Code generated by protoc-gen-go. DO NOT EDIT.').classification).toBe('generated');

    // Rust & Go
    expect(FileClassifier.classify('target/debug/libcore.rlib').classification).toBe('binary');
    expect(FileClassifier.classify('src/api.go', '// Code generated by sqlc. DO NOT EDIT.').classification).toBe('generated');

    // Java / Kotlin / Scala
    expect(FileClassifier.classify('.gradle/caches/modules-2/files.bin').classification).toBe('binary');
    expect(FileClassifier.classify('build/classes/java/main/App.class').classification).toBe('binary');
    expect(FileClassifier.classify('target/scala-2.13/app.jar').classification).toBe('binary');

    // C / C++ / C#
    expect(FileClassifier.classify('CMakeFiles/3.24.2/CMakeCCompiler.cmake').classification).toBe('generated');
    expect(FileClassifier.classify('Debug/app.pdb').classification).toBe('binary');
    expect(FileClassifier.classify('bin/Release/net8.0/app.dll').classification).toBe('binary');

    // Dart / Elixir / Swift
    expect(FileClassifier.classify('.dart_tool/package_config.json').classification).toBe('generated');
    expect(FileClassifier.classify('_build/dev/lib/app/ebin/app.beam').classification).toBe('binary');
    expect(FileClassifier.classify('.swiftpm/xcode/package.xcworkspace').classification).toBe('generated');

    // Source & Binary
    expect(FileClassifier.classify('assets/binary.bin').classification).toBe('binary');
    expect(FileClassifier.classify('src/app.ts').classification).toBe('source');
  });

  it('Scanner.scanDetailed rejects generated chunks, oversized files, and binary files before parsing', async () => {
    const scanner = new Scanner({
      rootDir: TEMP_ROOT,
      maxFileSize: '1MB'
    });

    const result = await scanner.scanDetailed();

    // 1. Valid source files MUST be discovered
    expect(result.files).toContain('src/app.ts');
    expect(result.files).toContain('src/utils.ts');

    // 2. Generated Next.js and _next bundles MUST NOT be in the scanned files
    expect(result.files).not.toContain('.next/static/chunks/huge-chunk.js');
    expect(result.files).not.toContain('public/_next/static/chunks/0v3lyuj75aq50.js');

    // 3. Oversized file (>1MB) MUST NOT be in the scanned files
    expect(result.files).not.toContain('src/large-file.js');

    // 4. Binary file MUST NOT be in the scanned files
    expect(result.files).not.toContain('assets/binary.bin');

    // 5. Check skipped telemetry
    const skippedLarge = result.skipped.find(s => s.path === 'src/large-file.js');
    expect(skippedLarge).toBeDefined();
    expect(skippedLarge?.reason).toBe('large');

    const skippedBinary = result.skipped.find(s => s.path === 'assets/binary.bin');
    expect(skippedBinary).toBeDefined();
    expect(skippedBinary?.reason).toBe('binary');
  });

  it('Kiteretsu.index executes safely with zero crashes and returns enriched skip stats', async () => {
    const summary = await kiteretsu.index();

    expect(summary.files).toBeGreaterThanOrEqual(2);
    expect(summary.symbols).toBeGreaterThanOrEqual(2);
    expect(summary.edges).toBeGreaterThanOrEqual(1);

    // Verify skip breakdown
    expect(summary.skippedLarge.length).toBeGreaterThanOrEqual(1);
    expect(summary.skippedLarge[0].path).toBe('src/large-file.js');

    expect(summary.skippedBinary.length).toBeGreaterThanOrEqual(1);
    expect(summary.skippedBinary).toContain('assets/binary.bin');

    expect(summary.failed.length).toBe(0);

    // Verify graph intelligence works on indexed files
    const analyzer = await kiteretsu.getAnalyzer();
    const blastRadius = await analyzer.getBlastRadius(path.join(TEMP_ROOT, 'src/utils.ts'));
    const normalizedBlast = blastRadius.map(p => path.relative(TEMP_ROOT, p).replace(/\\/g, '/'));
    expect(normalizedBlast).toContain('src/app.ts');
  });
});
